last_offer/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'last_offer.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^imagefit/', include('imagefit.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^', include('products.urls')),\

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import patterns, include, url
from products import views

urlpatterns = patterns('',
    # url(r'^/api$', views.products_list_api),
    url(r'^$', views.products_list, name='list'),
    url(r'^categories/(?P<category_id>\d+)$', views.category_list, name='show-category'),
    url(r'^specialoffers$', views.specialoffers_list, name='special'),
    url(r'^add$', views.add_offer, name="add"),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^shopping/(?P<name>[\w\-]+)/$', views.shop, name='shopping'), 
    url(r'^prodcuts/(?P<product_id>\d+)/$', views.view_product, name='product'), 
    url(r'^shop/(?P<name>[\w\-]+)/$', views.view_shop, name='shop'),
    url(r'^category/(?P<category_id>[\w\-]+)/$', views.category, name='category'),
    url(r'^update/(?P<product_id>[\w\-]+)/$', views.editoffer, name='update'),
    url(r'^register/$', views.register, name='register'),
    url(r'^cart/add$', views.add_to_cart, name='add-to-cart'),
    url(r'^cart/show$', views.show_cart, name='show-cart'),
    url(r'^cart/remove$', views.remove_from_cart, name='remove-from-cart'),
    url(r'^cart/clear$', views.clear_cart, name='clear-cart'),
    url(r'^cart/update$', views.update_cart, name='cart-update'),
    url(r'^about$', views.about, name='about'),
    url(r'^contact$', views.contact, name='contact'),
    url(r'^checkout$', views.checkout, name='checkout'),
    url(r'^transactions/list$', views.list_transactions, name='transactions-list'),
    url(r'^editprofile$', views.edit_profile, name='editprofile'),
    
    )  

products/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
import datetime

class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)

    # The additional attributes we wish to include.
    address = models.CharField("اﻻسم",max_length=255)
    mobile = models.CharField("رقم الموبايل",max_length=255,null=True)

    # Override the __unicode__() method to return out something meaningful!
    def __unicode__(self):
        return self.user.username

    class Meta:
      verbose_name = "ملف المستخدم"
      verbose_name_plural = "ملفات المستخدمين"

class Category(models.Model):
    name=models.CharField("اسم التصنيف",max_length=255, unique=True)


    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = "التصنيف"
        verbose_name_plural = "التصنيفات"

class Product(models.Model):
   #shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    name = models.CharField("اسم المنتج", max_length=255)
    # url = models.URLField("", null=True)
    before_price = models.FloatField("السعر قبل الخصم", null=True)
    price = models.FloatField("السعر الحالى", null=True)
    # end_date = models.DateField(null=True)
    is_active = models.BooleanField("مفعل", default=False)
    image = models.ImageField("صورة المنتج",null=True, upload_to='static/images/product')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    special = models.BooleanField("منتج خاص",default=False)
    desc = models.CharField("الوصف",max_length=255, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = "المنتج"
        verbose_name_plural = "المنتجات"


    # def save(self, *args, **kwargs):
    #     if self.before_price < self.price:
    #         raise ValueError("Updating the value of creator isn't allowed")
    #     super(Product, self).save(*args, **kwargs)

class TransactionItem(models.Model):
    product = models.ForeignKey(Product)
    quantity = models.IntegerField(null=True)
    subtotal = models.FloatField(null=True)
    transaction = models.ForeignKey('Transaction')

    
STATES = (
    (u'new',u'جديد'),
    (u'accepted',u'تم القبول'),
    (u'processing',u'قيد التنفيذ'),
    (u'done',u'تم'),
    )   
class Transaction(models.Model):
    user_profile = models.ForeignKey(UserProfile)
    status = models.CharField(choices=STATES, max_length=255)
    total = models.FloatField(null=True)
    receipt_no = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "عملية البيع"
        verbose_name_plural = "عمليات البيع"



class Message(models.Model):
    name = models.CharField("الاسم", max_length=255)
    email = models.EmailField("البريد الإلكترونى", max_length=70,)
    message_body =models.CharField("الرسالة", max_length=255)
   

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = "الرسالة"
        verbose_name_plural = "الرسائل"

products/forms.py
# -*- coding: utf-8 -*-
from django import forms
from products.models import *
import html5.forms.widgets as html5_widgets
from django.contrib.auth.models import User


class ProductForm(forms.ModelForm):
    # product_name = forms.CharField(label="اسم المنتج", max_length=255)
    # url = forms.CharField(label="رابط المنتج")
    # end_date = forms.DateField(label="تاريخ انتهاء العرض", required=False, widget=html5_widgets.DateInput)
    # image = forms.ImageField(label="صورة العرض", required=True)
    # price = forms.FloatField(label="السعر قبل الخصم")
    # after_price = forms.FloatField(label="السعر بعد الخصم")
    # special = forms.BooleanField(label="عرض مميز", required=False)
    # #desc = forms.CharField(widget=forms.Textarea)
    # desc = forms.CharField( label="الوصف")

    
    def clean(self):
        price = self.cleaned_data.get("price")
        before_price = self.cleaned_data.get("before_price")
        if price > before_price :
            msg = u"السعر قبل الخصم يجب أن يكون أكبر من أو يساوى السعر بعد الخصم"
            self._errors["before_price"] = self.error_class([msg])


    class Meta:
        model = Product
        fields = '__all__'
        # exclude = ('is_active','created_at', 'shop')
    


class UserForm(forms.ModelForm):
    username = forms.CharField(label="اسم المستخدم")
    email = forms.EmailField(label="البريد الإلكترونى")
    password = forms.CharField(label="كلمة المرور",widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password')

    
class MessageForm(forms.ModelForm):
    name = forms.CharField(label="الاسم")
    email = forms.EmailField(label="البريد الإلكترونى")
    message_body = forms.CharField(label="الرسالة", widget=forms.Textarea)
    class Meta:
        model = Message
        fields = ('name', 'email', 'message_body')

class UserProfileForm(forms.ModelForm):
    address = forms.CharField(label="العنوان")
    mobile = forms.CharField(label="رقم الموبايل") 
    class Meta:
        model = UserProfile
        fields = ('address', 'mobile') 

products/views.py
# -*- coding: utf-8 -*-            
from django.shortcuts import render
# from rest_framework.decorators import api_view, permission_classes
# from rest_framework import status, permissions
# from rest_framework.response import Response
from products.models import *
from products.forms import *
#from rango.forms import UserForm, UserProfileForm
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
import datetime
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse

import random 
from carton.cart import Cart
from django.shortcuts import redirect
import json




# @api_view(['GET'])
# @permission_classes((permissions.AllowAny,))
# def products_list_api(request):
#     if request.method == 'GET':
#         #get only open offers and order them
#         # and available job through date
#         #filter with active offers
#         products = Product.objects.filter(is_active=True)
#         serializer = ProductSerializer(products, many=True)
#         return Response(serializer.data)



# @api_view(['GET'])
# @permission_classes((permissions.AllowAny,))
#def shop_products_api(request, shop):
   # if request.method == 'GET':
    #    products = Products.objects.filter(shop=shop)
     #   serializer = OfferSerializer(products, many=True)
      #  return Response(serializer.data)

def products_list(request):
    # import ipdb; ipdb.set_trace()
    if request.method == 'GET':
        # offers=Offer.objects.filter(end_date__gte=datetime.date.today())

        products=Product.objects.filter(is_active=True).order_by('-created_at')
        if len(products) >= 10:
            latest = products[0:10]
        else:
            latest = products

        featured = products.filter(special=True)
        if len(featured) >= 5:
            featured = featured[0:5]


        paginator = Paginator(products,10) # Show 25 offer per page

        page = request.GET.get('page')
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            products = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            products = paginator.page(paginator.num_pages)
        context_dict = {'products': products,
                        'featured': featured,
                        'latest': latest,
                        'count':range(1, paginator.num_pages+1) }
        return render (request, "products/products.html", context_dict)

def about(request):
        return render (request, "products/about.html")
        

def category_list(request, category_id=None):
    # import ipdb; ipdb.set_trace()
    if request.method == 'GET':
        # offers=Offer.objects.filter(end_date__gte=datetime.date.today())
        # cat = Category.objects.get(id=category_id)
        # products=Product.objects.filter(category=cat)

        products=Product.objects.filter(category__id=category_id)
        paginator = Paginator(products,10) # Show 25 offer per page

        page = request.GET.get('page')
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            products = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            products = paginator.page(paginator.num_pages)
        context_dict = {'products': products, 'count':range(1, paginator.num_pages+1) }
        return render (request, "products/products.html", context_dict)


def specialoffers_list(request):
    # import pdb; pdb.set_trace()
    if request.method == 'GET':
        offers=Offer.objects.filter(end_date__gte=datetime.date.today(),special=True)
    paginator = Paginator(offers,2) # Show 25 offer per page

    page = request.GET.get('page')
    try:
        offers_page = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        offers_page = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        offers_page = paginator.page(paginator.num_pages)
        #date = datetime.datetime.now()
        #offers=Offer.objects.all()
    context_dict = {'offers': offers_page }
    return render (request, "offers/offers.html", context_dict)

@login_required
def add_offer(request):
    #shop = request.user.shop
    import ipdb;ipdb.set_trace();

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
           
            product= form.save(commit=False)
          
            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and put it in the UserProfile model.
            if 'image' in request.FILES:
                product.image = request.FILES['image']

            # Now we save the UserProfile model instance.
                product.save()
            return HttpResponseRedirect(reverse('list'))
            

        else:
            print form.errors
    else:
        form = ProductForm()
    return render(request, "products/add.html", {'form': form})



def register(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('list'))
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        shop_form = ShopForm(data=request.POST)
        if user_form.is_valid() and shop_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            shop = shop_form.save(commit=False)
            shop.user = user
            shop.save()
            registered = True
            return HttpResponseRedirect(reverse('list'))
        else:
            user_form.errors, shop_form.errors
    else:
        user_form = UserForm()
        shop_form = ShopForm()
    return render(request,
            'offers/register.html',
            {'user_form': user_form, 'shop_form': shop_form, 'registered': registered} )


def user_login(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('list'))
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('list'))
            else:
                return render (request, 'products/error.html', {'error_code': 'غير نشط','error_message': 'هذا الحساب غير مفعل'})
        else:
            return render (request, 'products/login.html', {'error': 'بيانات التسجيل غير صحيحة'})

    else:
        return render (request, 'products/login.html', {})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('list'))


def shop(request, name):

    # Create a context dictionary which we can pass to the template rendering engine.
    context_dict = {}

    try:
       # import pdb; pdb.set_trace()
        shop = Shop.objects.get(name=name)
        context_dict['name']=shop.name
        offers = Offer.objects.filter(shop=shop)
        context_dict['offers'] = offers
        context_dict['shop'] = shop
    except Shop.DoesNotExist:
        print "Shop does not exist"
    return render(request, 'offers/shop.html', context_dict)






@login_required
def view_product(request, product_id):
    # Create a context dictionary which we can pass to the template rendering engine.
    context_dict = {}

    try:
        product= Product.objects.get(id=product_id)
        context_dict['product'] = product
        # We also add the category object from the database to the context dictionary.
        # We'll use this in the template to verify that the category exists.
       # context_dict['shop'] = shop
    except Product.DoesNotExist:
        # We get here if we didn't find the specified category.
        # Don't do anything - the template displays the "no category" message for us.
        pass

    # Go render the response and return it to the client.
    return render(request, 'products/view_product.html', context_dict)





def view_shop(request, name):

    # Create a context dictionary which we can pass to the template rendering engine.
    context_dict = {}

    try:
        # import pdb; pdb.set_trace()
        shop= Shop.objects.get(name=name)
        context_dict['shop'] = shop
    except Shop.DoesNotExist:
        
        print "ERROR"

    # Go render the response and return it to the client.
    return render(request, 'offers/view_shop.html', context_dict)




def category(request, category_id):

    # Create a context dictionary which we can pass to the template rendering engine.
    context_dict = {}

    try:
       # import pdb; pdb.set_trace()
        category = get_object_or_404(Category, category_id=category_id)
        offers = Offer.objects.filter(category=category)
        context_dict['category_id']=category_id
        context_dict['offers']=offers
    except Category.DoesNotExist:
        print "Shop does not exist"
    return render(request, 'products/category.html', context_dict)



@login_required
def editoffer(request,product_id):
    if request.POST:
        offerform = OfferForm(request.POST)

        if offerform.is_valid():

            offer = Offer.objects.get(id=product_id)
            offerform = OfferForm(request.POST, instance = offer)
            offerform.save()

templates/products/add.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap %}
{% block title %} All Offers  {% endblock %}
{% block content %}


<legend>إضافة عرض</legend>
  <form id="offer_form"  method="post" class="form-horizontal" enctype="multipart/form-data" onsubmit="return is_valid();"> 

            {% csrf_token %}
            {{ form|bootstrap_horizontal }}
            
            <div class="form-group">
      <div class="col-sm-10 col-sm-offset-2">
            <input type="submit" name="submit" value="إرسال الطلب"  class="btn btn-primary btn-lg" />
            </div>
            </div>
        </form>
</div>


<script type="text/javascript">
$( document ).ready(function() {
	
	});
function is_valid(){
	x = parseInt(document.getElementById("id_price").value)
	y = parseInt(document.getElementById("id_after_price").value)
	if(y > x ){
		alert("السعر بعد الخصم يجب أن يكون أقل من أو يساوى السعر قبل الخصم")
		return false;
	}else {
		url =  document.getElementById("id_url");
		if(!url.value.startsWith("http://")){
			url.value = "http://" + url.value
		}
		return true;

	}
}

</script>
{% endblock %}

templates/products/category.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} All Offers  {% endblock %}
{% block content %}


<div class="row">
  <legend>{{name}}</legend>
  {% if products %}
  
  {%for  product in offers%}
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      {% if offer.image %}
      <img src="/{{offer.image.url}}" style="width:300px;height:200px;">
      {% else %}
      
      {% endif %}
      <div class="caption">
        <h3>{{offer.product_name}}</h3>
        <p><ul>
          <li class="price">{{offer.price}}</li>
          <li class="after_price">{{offer.after_price}}</li>
          <li>{{offer.end_date}}</li>
          <li>
          <!-- <a href="{% url 'shop' offer.shop %}">{{ offer.shop }}</a></li> -->
          
          <a href="/products/register/">Register Here</a>

        </ul>
      </p>

    </div>
  </div>
</div>
  {%endfor%}


{% endif %}
</div>




{% endblock %}

templates/products/contact.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap %}
{% block title %} All Offers  {% endblock %}
{% block content %}

<!-- <div >
    <legend>أرسل رسالة</legend>
    <form id="message_form"  method="post" class="form-horizontal"> 

        {% csrf_token %}
        {{ form|bootstrap_horizontal }}

        <div class="form-group">
          <div class="col-sm-10 col-sm-offset-2">
            <input type="submit" name="submit" value="إرسال"  class="btn btn-primary btn-lg" />
        </div>
    </div>
</form>
</div>
-->


<div id="title-bg">
    <div class="title">اتصل بنا</div>
</div>
<div class="row">
    <div class="col-md-4">
        <p class="page-content">
            للمساعدة يمكنك الاتصال بنا من خلال رقم هذا الهاتف أو أرسال رسالة من خلال ملى النموذج 
        </p>
        <ul class="contact-widget">
            <!-- <li class="fphone">+387 123 456, +387 123 456 <br /> +387 123 456</li> -->
            <li class="fmobile">00966-500-787-80</li>
            <li class="fmail lastone">your@email.com<br />customer.care@mail.com</li>
        </ul>
    </div>

    <div class="col-md-8">
        <!-- <legend>أرسل رسالة</legend> -->
        <form id="message_form"  method="post" class="form-horizontal"> 

            {% csrf_token %}
            {{ form|bootstrap_horizontal }}

            <div class="form-group">
              <div class="col-sm-10 col-sm-offset-2">
                <input type="submit" name="submit" value="إرسال"  class="btn btn-primary btn-lg" />
            </div>
        </div>
    </form>
</div>
</div>







<!-- 
        <div class="col-md-4">
        <div id="title-bg">
            <div class="title">أرسل رسالة</div>
        </div>
        <div class="qc">
            <form role="form">
                <div class="form-group">
                    <label for="name">Name<span>*</span></label>
                    <input type="text" class="form-control" id="name" >
                </div>
                <div class="form-group">
                    <label for="email">Email<span>*</span></label>
                    <input type="email" class="form-control" id="email" >
                </div>
                <div class="form-group">
                    <label for="text">Messages<span>*</span></label>
                    <textarea class="form-control" id="text" ></textarea>
                </div>
                <button type="submit" class="btn btn-default btn-red btn-sm">Submit</button>
            </form>
        </div>
        <div class="spacer"></div>
        </div>

    -->
    {% endblock %} 

templates/products/edit.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} All Offers  {% endblock %}
{% block content %}
{% load bootstrap %}

<form id="user_form" method="post" action="{% url 'editprofile' %}"
enctype="multipart/form-data" class="form-horizontal">

{% csrf_token %}

            <!-- Display each form. The as_p method wraps each element in a paragraph
                 (<p>) element. This ensures each element appears on a new line,
                 making everything look neater. -->
                 {{ profile_form|bootstrap_horizontal}}
                 <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <!-- Provide a button to click to submit the form. -->
                        <input class="btn btn-default btn-yellow"type="submit" name="submit" value="تعديل" />
                    </div>
                </div>
            </form>
            {% endblock %}

templates/products/editoffer.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap %}
{% block title %} All Offers  {% endblock %}
{% block content %}


<div >
<legend>إضافة عرض</legend>
  <form id="offer_form"  method="post" class="form-horizontal" enctype="multipart/form-data"> 

            {% csrf_token %}
            {{ form|bootstrap_horizontal }}
            
            <div class="form-group">
      <div class="col-sm-10 col-sm-offset-2">
            <input type="submit" name="submit" value="إرسال الطلب"  class="btn btn-primary btn-lg" />
            </div>
            </div>
        </form>
</div>

{% endblock %} 

templates/products/register_page.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} All Offers  {% endblock %}
{% block content %}
{% load bootstrap %}

<form id="user_form" method="post" action="/register/"
enctype="multipart/form-data" class="form-horizontal">

{% csrf_token %}

            <!-- Display each form. The as_p method wraps each element in a paragraph
                 (<p>) element. This ensures each element appears on a new line,
                 making everything look neater. -->
                 {{ user_form|bootstrap_horizontal}}
                 {{ profile_form|bootstrap_horizontal}}
                 <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <!-- Provide a button to click to submit the form. -->
                        <input class="btn btn-default btn-yellow"type="submit" name="submit" value="تسجيل" />
                    </div>
                </div>
            </form>
            {% endblock %}

templates/products/shop.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} All Offers  {% endblock %}
{% block content %}

<div class="row">

   {% if shop %}
   <h1>{{ shop.name }}</h1>
   {% if offers %}
   <ul>
    {% for offer in offers %}
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            {% if offer.image %}
            <img src="/{{offer.image.url}}" style="width:300px;height:200px;">
            {% else %}
            {% endif %}
            <div class="caption">
                <h3>{{offer.product_name}}</h3>
                <p><ul>
                    <li class="price">{{offer.price}}</li>
                    <li class="after_price">{{offer.after_price}}</li>
                    <li>{{offer.end_date}}</li>
                    <li>{{offer.cat_name}}</li>

                </ul></p>
            </div>
        </div>   
    </div>
    {% endfor %}
</ul>
{% else %}
<strong>No pages currently in category.</strong>
{% endif %}
{% else %}
The specified category {{ shop.name }} does not exist!
{% endif %}
{% endblock %}

templates/products/specialoffers.html
{% extends 'base.html' %}
{% load pagination_tags %}
{% load staticfiles %}
{% block title %} All Offers  {% endblock %}
{% block content %}


<div class="row">
<legend>عروضنا</legend>
  {% if offers %}
  {% autopaginate offers 2 %}
  {% for offer in offers %}
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
    {% if offer.image %}
      <img src="/{{offer.image.url}}" style="width:300px;height:200px;">
      {% else %}
      
      {% endif %}
      <div class="caption">
        <h3>{{offer.product_name}}</h3>
        <p><ul>
            <li class="price">{{offer.price}}</li>
            <li class="after_price">{{offer.after_price}}</li>
            <li>{{offer.end_date}}</li>
            <li>{{offer.shop}}</li>
            <li>{{offer.category.name}}</li>
            <li>مميز</li>


        </ul></p>

      </div>
    </div>
  </div>
    {% endfor %}
    {% paginate %}
    {% endif %}
</div>




{% endblock %}

templates/products/transactions.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} All Offers  {% endblock %}
{% block content %}
{% load carton_tags %}


<div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="page-title-wrap">
                    <div class="page-title-inner">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="bread"><a href="{% url 'list'%}">الرئيسية</a> &rsaquo; سلتى</div>
                            <div class="bigtitle">مشترياتى</div>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="title-bg">
            <div class="title">جميع المشتريات</div>
        </div>
        {% for transaction in transactions %}
        <h4> {{transaction.created_at}} - الإجمالى : {{ transaction.total}}</h4>
        <div class="table-responsive">
            <table id="cart-table" class="table table-bordered chart" dir="ltr">
                <thead>
                    <tr>
                        <th>رقم المنتج</th>
                        <th>المنتج</th>
                        <th>صورة المنتج</th>
                        <th>التصنيف</th>
                        <th>سعر الوحدة</th>
                        <th>الكمية</th>
                        <th>اﻻجمالى</th>
                    </tr>
                </thead>
                
                <tbody>
                {% for item in transaction.transactionitem_set.all %}
                    <tr>
                        <td class="product-id" valign="middle">{{item.product.id}}</td>
                        <td valign="middle">{{item.product.name}}</td>
                        <td valign="middle"><img src="{{item.product.image.url}}" width="100" /></td>
                        <td valign="middle">{{item.product.category}}</td>
                        <td>{{item.product.price}}</td>
                        <td class="product-qty"><center><span>{{item.quantity}} </span></center></td>
                        <td>
                            <span id="{{item.product.id}}_total"> {{item.subtotal}} </span>
                        </td>
          
                        </tr>
                    {% endfor %}
                    
                </tbody>
            </table>
            {% endfor %}
        </div>
        <div class="spacer"></div>
    </div>

{% endblock %}

templates/products/view_shop.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} All Offers  {% endblock %}
{% block content %}


<legend>{{shop.name}}</legend>
  {% if shop %}

<div class="row">

  <div class="form-group">
      <label for="user" class="col-sm-2 
 control-label" >اسم المستخدم</label>
      <div class=" col-sm-6 ">
        <input type="text" name="user" id="user" value={{shop.user}}  readonly class="form-control" />
      </div>
    </div>
    </div>

<div class="row">

    <div class="form-group">
      <label for="name" class="col-sm-2 control-label" >اسم المتجر</label>
      <div class=" col-sm-6 ">
        <input type="text" name="name" id="name" value={{shop.name}}  readonly class="form-control" />
      </div>
    </div>
    </div> 

      
    <div class="row">

    <div class="form-group">
      <label for="url" class="col-sm-2 control-label" >عنوان المتجر</label>
      <div class=" col-sm-6 ">
        <input type="datefield" name="url" id="url" value={{shop.url}}  readonly class="form-control" />
      </div>
    </div>
    </div>


    


    

  
    {% endif %}




{% endblock %}